{
    "name": "USL Documents",
    "summary": "Native Odoo document work backed by Paperless-ngx",
    "description": "Native Odoo document workflows backed by the Paperless-ngx archive.",
    "version": "saas~19.3.1.8.8",
    "category": "Productivity/Documents",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "web",
        "mail",
        "account",
        "hr_expense",
        "project",
        "hr",
        "usl_pocketid",
        "usl_locale",
    ],
    "data": [
        "security/usl_documents_security.xml",
        "security/ir.model.access.csv",
        "views/usl_document_views.xml",
        "views/usl_document_metadata_views.xml",
        "views/business_record_views.xml",
        "views/res_config_settings_views.xml",
        "data/usl_documents_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "usl_documents/static/src/document_preview.js",
            "usl_documents/static/src/document_preview.xml",
            "usl_documents/static/src/documents_loader.js",
            "usl_documents/static/src/open_documents_field.xml",
            "usl_documents/static/src/attachment_list_patch.js",
            "usl_documents/static/src/attachment_list_patch.xml",
        ],
        "usl_documents.assets_workspace": [
            "usl_documents/static/src/documents_app.js",
            "usl_documents/static/src/documents_app.xml",
            "usl_documents/static/src/documents_app.scss",
        ],
        "web.assets_unit_tests": [
            "usl_documents/static/tests/attachment_list_patch.test.js",
            ("include", "usl_documents.assets_workspace"),
            "usl_documents/static/tests/documents_app.test.js",
        ],
    },
    "application": True,
    "installable": True,
}
