{
    "name": "USL Accounting Migration",
    "summary": "Source-trace, import-run and discrepancy records for USL accounting reconstruction.",
    "version": "19.0.1.0.0",
    "category": "Accounting/Accounting",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "account",
        "account_asset_management",
        "account_payment",
        "account_financial_report",
        "account_reconcile_oca",
        "account_statement_import_file",
        "account_tax_balance",
        "analytic",
        "hr_expense",
        "l10n_fr_account",
        "mis_builder",
        "partner_statement",
    ],
    "data": [
        "security/rebuild_account_security.xml",
        "security/ir.model.access.csv",
        "data/currency_rate_provider.xml",
        "data/french_declaration_rules.xml",
        "data/usl_mis_reports.xml",
        "views/rebuild_account_migration_views.xml",
        "views/account_closing_declaration_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "rebuild_account_migration/static/src/js/account_move_upload_controls.js",
            "rebuild_account_migration/static/src/js/accounting_home_action.js",
            "rebuild_account_migration/static/src/xml/hr_expense_reviewer_controls.xml",
        ],
    },
    "application": False,
    "installable": True,
}
