{
    "name": "USL Accounting",
    "summary": (
        "USL Accounting cockpit, controls, reports, declarations, "
        "and audit evidence."
    ),
    "version": "saas~19.3.1.13.14",
    "category": "Accounting/Accounting",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "account",
        "account_asset_management",
        "account_payment",
        "account_financial_report",
        "account_reconcile_oca",
        "account_statement_import_camt",
        "account_statement_import_file",
        "account_statement_import_qif",
        "account_statement_import_sheet_file_xlsx",
        "account_tax_balance",
        "analytic",
        "hr_expense",
        "l10n_fr_account",
        "l10n_fr_pdp",
        "mail",
        "partner_statement",
        "spreadsheet_account",
        "usl_accounting",
        "usl_document_templates",
        "usl_expense_batch",
        "usl_platform_billing",
        "usl_platform_billing_pocketid",
        "usl_pocketid",
    ],
    "data": [
        "security/rebuild_account_security.xml",
        "security/ir.model.access.csv",
        "data/currency_rate_provider.xml",
        "data/french_declaration_rules.xml",
        "data/french_declaration_rules_extended.xml",
        "data/accounting_framework.xml",
        "data/einvoice_readiness.xml",
        "views/rebuild_account_migration_views.xml",
        "views/account_closing_declaration_views.xml",
        "views/accounting_framework_views.xml",
        "views/analytic_reporting_views.xml",
        "views/account_direction_guard_views.xml",
        "views/einvoice_readiness_views.xml",
        "views/accounting_action_guidance_views.xml",
        "views/bank_statement_hygiene_views.xml",
        "views/reconciliation_model_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "rebuild_account_migration/static/src/js/account_move_upload_controls.js",
            "rebuild_account_migration/static/src/js/accounting_home_action.js",
            "rebuild_account_migration/static/src/js/accounting_report_action.js",
            "rebuild_account_migration/static/src/js/expense_upload_navigation.js",
            "rebuild_account_migration/static/src/js/matching_badge_field.js",
            "rebuild_account_migration/static/src/js/reconcile_data_presentation.js",
            "rebuild_account_migration/static/src/js/reconcile_navigation.js",
            "rebuild_account_migration/static/src/js/readonly_accounting_chatter.js",
            "rebuild_account_migration/static/src/scss/account_review_state_selection_badge.scss",
            "rebuild_account_migration/static/src/scss/accounting_controls.scss",
            "rebuild_account_migration/static/src/scss/accounting_overview.scss",
            "rebuild_account_migration/static/src/scss/accounting_report.scss",
            "rebuild_account_migration/static/src/scss/bank_matching.scss",
            "rebuild_account_migration/static/src/scss/interaction_cursors.scss",
            "rebuild_account_migration/static/src/scss/matching_badge.scss",
            "rebuild_account_migration/static/src/scss/reconciliation_model.scss",
            "rebuild_account_migration/static/src/xml/account_review_state_selection_badge.xml",
            "rebuild_account_migration/static/src/xml/accounting_report_action.xml",
            "rebuild_account_migration/static/src/xml/hr_expense_reviewer_controls.xml",
            "rebuild_account_migration/static/src/xml/matching_badge_field.xml",
            "rebuild_account_migration/static/src/xml/reconcile_data_presentation.xml",
            "rebuild_account_migration/static/src/xml/readonly_accounting_chatter.xml",
        ],
        "web.assets_backend_lazy": [
            "rebuild_account_migration/static/src/js/analytic_pivot_pdf.js",
            "rebuild_account_migration/static/src/xml/analytic_pivot_pdf.xml",
        ],
        "web.assets_unit_tests": [
            "rebuild_account_migration/static/tests/bank_matching_navigation.test.js",
            "rebuild_account_migration/static/tests/bank_matching_selection.test.js",
            "rebuild_account_migration/static/tests/interaction_cursors.test.js",
            "rebuild_account_migration/static/tests/matching_badge.test.js",
            "rebuild_account_migration/static/tests/reconcile_data_presentation.test.js",
            "rebuild_account_migration/static/tests/report_presentation.test.js",
            "rebuild_account_migration/static/tests/review_state_badge.test.js",
            "rebuild_account_migration/static/tests/transactions_navigation.test.js",
        ],
        "web.assets_tests": [
            "rebuild_account_migration/static/tests/tours/einvoice_reception_tours.js",
        ],
    },
    "application": False,
    "installable": True,
}
