{
    "name": "USL Accounting Foundation",
    "summary": "Shared operational extensions for the USL Accounting product",
    "version": "saas~19.3.2.0.1",
    "category": "Accounting/Accounting",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "account",
        "account_payment",
        "account_reconcile_oca",
        "account_statement_import_ofx",
        "analytic",
        "hr_expense",
        "spreadsheet_account",
        "usl_expense_batch",
        "usl_locale",
    ],
    "data": [
        "security/expense_bank_matching_security.xml",
        "security/immediate_settlement_security.xml",
        "security/bank_statement_ingestion_security.xml",
        "security/ir.model.access.csv",
        "data/immediate_settlement_sequence.xml",
        "data/bank_ingestion_cron.xml",
        "wizard/expense_bank_match_wizard_views.xml",
        "wizard/bank_statement_review_wizard_views.xml",
        "views/bank_statement_ingestion_views.xml",
        "views/bank_statement_review_views.xml",
        "views/hr_expense_bank_matching_views.xml",
        "views/expense_batch_reporting_views.xml",
        "views/immediate_settlement_views.xml",
        "views/res_users_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "usl_accounting/static/src/js/immediate_settlement.js",
            "usl_accounting/static/src/scss/payment_suggestions.scss",
            "usl_accounting/static/src/xml/account_payment_suggestions.xml",
        ],
        "web.assets_unit_tests": [
            "usl_accounting/static/tests/payment_suggestions.test.js",
        ],
        "web.assets_tests": [
            "usl_accounting/static/tests/tours/immediate_settlement_tour.js",
        ],
    },
    "application": False,
    "installable": True,
    "post_init_hook": "post_init_hook",
}
