"""Render the reference pages of the user guide from the registry facts.

``scripts/odoo/docs_reference.py`` extracts ``usl-docs-reference/v1`` from a
running product database. This module turns it into
``docs/users/reference/generated/*.md``, deterministically, so the pages are
committed and a CI check proves they are current. The hand-written reference
pages beside them stay: they explain; these enumerate.
"""

from __future__ import annotations

import json
from pathlib import Path

from operations.user_docs import ROOT, USERS, frontmatter

SCHEMA = "usl-docs-reference/v1"
DIRECTORY = Path("reference") / "generated"
GENERATED_NOTE = "<!-- Generated by scripts/docs-reference from the product's registry. Change the code, then run `make docs-reference`. -->"


class DocsReferenceError(RuntimeError):
    """The reference document is malformed."""


def load(path):
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or payload.get("schema") != SCHEMA:
        raise DocsReferenceError(f"{path}: expected {SCHEMA}")
    return payload


def _front(title, description, source, persona="everyone"):
    return frontmatter().dump({
        "title": title,
        "type": "reference",
        "description": description,
        "lang": "en",
        "persona": persona,
        "source": source,
        "generated": True,
    })


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _page(title, description, source, body_lines, persona="everyone"):
    body = "\n".join([GENERATED_NOTE, "", f"# {title}", "", description, "", *body_lines]).rstrip("\n") + "\n"
    return _front(title, description, source, persona) + "\n" + body


def _module_sources(modules):
    return [f"custom-addons/{module}" for module in sorted({module for module in modules if module})]


# --- Pages -------------------------------------------------------------------


def _module_of(model):
    return model["module"] or next((field["module"] for field in model["fields"] if field["module"]), "")


def render_fields_for(payload, module):
    lines = []
    models = [model for model in payload["models"] if any(field["module"] == module for field in model["fields"])]
    for model in models:
        fields = [field for field in model["fields"] if field["module"] == module]
        heading = model["description"] or model["model"]
        owner = "defined by this module" if model["module"] == module else f"extended by this module (defined by `{model['module'] or 'Odoo'}`)"
        lines.extend([
            f"## {heading}",
            "",
            f"`{model['model']}`, {owner}."
            + (" Transient: the record lives only while its dialog is open." if model["transient"] else ""),
            "",
        ])
        if model["explanation"] and model["module"] == module:
            lines.extend([model["explanation"], ""])
        lines.extend([
            "| Field | Type | Required | Meaning |",
            "| --- | --- | --- | --- |",
        ])
        for field in fields:
            kind = field["type"]
            if field["relation"]:
                kind = f"{kind} → `{field['relation']}`"
            meaning = field["help"] or ""
            if field["selection"]:
                values = ", ".join(f"**{item['label']}**" for item in field["selection"])
                meaning = f"{meaning} Values: {values}." if meaning else f"Values: {values}."
            lines.append(
                f"| **{_cell(field['label'])}** (`{field['name']}`) | {_cell(kind)} | {'yes' if field['required'] else ''} | {_cell(meaning)} |",
            )
        lines.append("")
    return _page(
        f"Fields: {module}",
        f"Every field `{module}` defines or adds to Odoo, by model, with its label, type and meaning.",
        [f"custom-addons/{module}"],
        lines,
    )


def field_modules(payload):
    return sorted({field["module"] for model in payload["models"] for field in model["fields"] if field["module"]})


def render_states(payload):
    lines = []
    for state in payload["states"]:
        lines.extend([f"## {state['description'] or state['model']}: {state['label']}", ""])
        if state["help"]:
            lines.extend([state["help"], ""])
        for item in state["values"]:
            lines.append(f"- **{item['label']}** (`{item['value']}`)")
        lines.append("")
    return _page(
        "States",
        "The lifecycle values of every product record, in the order the product moves through them.",
        _module_sources(payload["coverage"].keys()),
        lines,
    )


def render_roles(payload):
    lines = [
        "| Role | Category | Includes | Purpose |",
        "| --- | --- | --- | --- |",
    ]
    for group in payload["groups"]:
        includes = ", ".join(f"`{name}`" for name in group["implies"]) or ""
        lines.append(f"| **{_cell(group['name'])}** (`{group['full_name']}`) | {_cell(group['category'])} | {includes} | {_cell(group['comment'])} |")
    lines.append("")
    return _page(
        "Roles",
        "The access groups the product adds, what each includes and what it is for.",
        _module_sources(group["module"] for group in payload["groups"]),
        lines,
        persona="administrator",
    )


def render_menus(payload):
    lines = [
        "| Menu | Opens | Visible to |",
        "| --- | --- | --- |",
    ]
    for menu in payload["menus"]:
        opens = f"{_cell(menu['action'])}" if menu["action"] else "a sub-menu"
        visible = ", ".join(f"`{name}`" for name in menu["groups"]) or "everyone with the application"
        lines.append(f"| **{_cell(menu['path'])}** | {opens} | {visible} |")
    lines.append("")
    return _page(
        "Menus",
        "Every menu the product adds, what it opens and who sees it.",
        _module_sources(menu["module"] for menu in payload["menus"]),
        lines,
    )


def render_settings(payload):
    lines = [
        "| Setting | Type | Meaning | Module |",
        "| --- | --- | --- | --- |",
    ]
    for field in payload["settings"]:
        meaning = field["help"] or ""
        if field["selection"]:
            values = ", ".join(f"**{item['label']}**" for item in field["selection"])
            meaning = f"{meaning} Values: {values}." if meaning else f"Values: {values}."
        lines.append(f"| **{_cell(field['label'])}** (`{field['name']}`) | {_cell(field['type'])} | {_cell(meaning)} | `{field['module']}` |")
    lines.append("")
    return _page(
        "Settings",
        "The options the product adds to Settings, with their meaning.",
        _module_sources(field["module"] for field in payload["settings"]),
        lines,
        persona="administrator",
    )


def render_coverage(payload):
    lines = [
        "How much of the product's stored fields carry a tooltip (`help=`). The",
        "generated field reference is only as good as this number; raising it is",
        "documentation work done in the code.",
        "",
        "| Module | Fields with help | Fields | Coverage |",
        "| --- | --- | --- | --- |",
    ]
    for module, item in payload["coverage"].items():
        ratio = f"{100 * item['documented'] / item['total']:.0f} %" if item["total"] else "n/a"
        lines.append(f"| `{module}` | {item['documented']} | {item['total']} | {ratio} |")
    lines.append("")
    return _page(
        "Field help coverage",
        "How many of the product's fields explain themselves with a tooltip, per module.",
        _module_sources(payload["coverage"].keys()),
        lines,
        persona="administrator",
    )


PAGES = {
    "states.md": render_states,
    "roles.md": render_roles,
    "menus.md": render_menus,
    "settings.md": render_settings,
    "help-coverage.md": render_coverage,
}


def rendered_pages(payload):
    pages = {DIRECTORY / name: render(payload) for name, render in PAGES.items()}
    for module in field_modules(payload):
        pages[DIRECTORY / f"fields-{module.replace('_', '-')}.md"] = render_fields_for(payload, module)
    return pages


def render_all(reference_path, docs_root=USERS):
    written = []
    for relative, text in rendered_pages(load(reference_path)).items():
        path = docs_root / relative
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            written.append(path)
    return written


def check_all(reference_path, docs_root=USERS):
    findings = []
    for relative, text in rendered_pages(load(reference_path)).items():
        path = docs_root / relative
        try:
            shown = path.relative_to(ROOT).as_posix()
        except ValueError:
            shown = path.as_posix()
        if not path.exists():
            findings.append((shown, "missing; run `make docs-reference`"))
        elif path.read_text(encoding="utf-8") != text:
            findings.append((shown, "differs from the registry; run `make docs-reference`"))
    return findings
