"""Index and check the repository documentation.

Two things drift when people maintain them by hand: the landing pages that
list every guide, and the agreement between where a page lives and what it
claims to be. Both are derived here from one source, the front matter each
page carries, so the in-product viewer, ``docs/users/README.md``,
``docs/llms.txt`` and the decision index can never disagree.

``scripts/docs-index`` writes the generated files; ``scripts/check-docs``
proves they are current and that every page is well formed. The parser is the
module the Odoo viewer uses, loaded by path so the runtime and the repository
share one definition.
"""

from __future__ import annotations

import importlib.util
import posixpath
import re
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
USERS = DOCS / "users"
DECISIONS = DOCS / "product" / "decisions"
FRONTMATTER_MODULE = ROOT / "custom-addons" / "usl_docs" / "tools" / "frontmatter.py"
GENERATED_NOTICE = "<!-- Generated by scripts/docs-index from page front matter. Edit the pages, not this file. -->"
LINK_RE = re.compile(r"(?<!\!)\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)\)")
DECISION_FILE_RE = re.compile(r"^(\d{4})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
DECISION_STATUSES = ("proposed", "accepted", "deprecated", "superseded")

SECTIONS = (
    ("tutorial", "Learn", "Start here if the product is new to you."),
    ("how-to", "Complete a task", "Goal-shaped steps for work you already understand."),
    ("reference", "Look something up", "What the screens, statuses and settings mean."),
    ("explanation", "Understand the design", "Why the product behaves the way it does."),
)
PERSONA_LABELS = {
    "everyone": "everyone",
    "ceo": "the CEO",
    "accountant": "accountants",
    "finance_operator": "finance operators",
    "employee": "employees",
    "manager": "managers",
    "administrator": "administrators",
}


def frontmatter():
    spec = importlib.util.spec_from_file_location("usl_docs_frontmatter", FRONTMATTER_MODULE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@dataclass
class Page:
    path: str
    data: dict
    body: str
    problems: list = field(default_factory=list)

    @property
    def title(self):
        return self.data.get("title") or self.path

    @property
    def type(self):
        return self.data.get("type")


def load_pages(root=USERS, fm=None):
    fm = fm or frontmatter()
    pages = []
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).as_posix()
        if rel == "README.md":
            continue
        text = path.read_text(encoding="utf-8")
        try:
            data, body = fm.split(text)
            problems = fm.validate(data, rel)
        except fm.FrontMatterError as error:
            data, body, problems = {}, text, [str(error)]
        pages.append(Page(rel, data, body, problems))
    return pages


def _link_targets(body):
    for match in LINK_RE.finditer(body):
        yield match.group(2), False
    for match in IMAGE_RE.finditer(body):
        yield match.group(2), True


def check_links(page, root):
    """Return the relative links and images on ``page`` that resolve nowhere."""
    problems = []
    for target, is_image in _link_targets(page.body):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        clean = target.split("#", 1)[0].split("?", 1)[0]
        if not clean:
            continue
        if clean.startswith("/"):
            problems.append(f"absolute link {target!r} (the viewer blanks it)")
            continue
        resolved = posixpath.normpath(posixpath.join(posixpath.dirname(page.path), clean))
        if resolved.startswith(".."):
            problems.append(f"link {target!r} escapes docs/users")
            continue
        if not (root / resolved).is_file():
            kind = "image" if is_image else "link"
            problems.append(f"{kind} {target!r} does not exist")
    return problems


# --- docs/users/README.md -----------------------------------------------


def render_users_index(pages):
    lines = [
        GENERATED_NOTICE,
        "",
        "# USL user guide",
        "",
        "This guide ships with the release you are using. Pages marked as tested are",
        "generated from the product's own browser journeys; the others are written by",
        "hand and say so at the bottom.",
        "",
    ]
    by_type = {}
    for page in pages:
        by_type.setdefault(page.type, []).append(page)
    for key, heading, intro in SECTIONS:
        entries = sorted(by_type.get(key, []), key=lambda page: page.title.lower())
        if not entries:
            continue
        lines.extend([f"## {heading}", "", intro, ""])
        for page in entries:
            note = ""
            if page.data.get("lang", "en") != "en":
                note = f" ({page.data['lang'].upper()})"
            persona = page.data.get("persona")
            audience = f" (for {PERSONA_LABELS[persona]})" if persona and persona != "everyone" else ""
            lines.append(f"- [{page.title}]({page.path}){note}: {page.data.get('description', '')}{audience}")
        lines.append("")
    lines.extend([
        "The active company controls the documents and values you see. Use the company",
        "switcher in the top bar before starting a task for another company.",
        "",
    ])
    return "\n".join(lines)


# --- docs/llms.txt --------------------------------------------------------


def render_llms_txt(pages, decisions):
    lines = [
        "# USL Odoo Distribution",
        "",
        "> User guide and decision records for the USL Odoo distribution. Pages carry",
        "> front matter (title, type, description, lang, persona, journey, source,",
        "> generated) that says what each one is for and whether a test proves it.",
        "",
        "Paths are relative to the repository root. In a running product the guide is",
        "served at `/usl/user-docs/<path under docs/users>`; add `?format=md` or send",
        "`Accept: text/markdown` to read the committed Markdown.",
        "",
    ]
    by_type = {}
    for page in pages:
        by_type.setdefault(page.type, []).append(page)
    labels = {"tutorial": "Tutorial", "how-to": "How-to guides", "reference": "Reference", "explanation": "Explanation"}
    for key in ("tutorial", "how-to", "reference"):
        entries = sorted(by_type.get(key, []), key=lambda page: page.title.lower())
        if not entries:
            continue
        lines.extend([f"## {labels[key]}", ""])
        for page in entries:
            lines.append(f"- [{page.title}](docs/users/{page.path}): {page.data.get('description', '')}")
        lines.append("")
    lines.extend(["## Decisions", ""])
    for decision in decisions:
        lines.append(f"- [{decision['title']}](docs/product/decisions/{decision['file']}): {decision['status']}, {decision['date']}")
    lines.append("")
    entries = sorted(by_type.get("explanation", []), key=lambda page: page.title.lower())
    if entries:
        lines.extend(["## Optional", ""])
        for page in entries:
            lines.append(f"- [{page.title}](docs/users/{page.path}): {page.data.get('description', '')}")
        lines.append("")
    return "\n".join(lines)


# --- docs/product/decisions -----------------------------------------------


def load_decisions(root=DECISIONS):
    """Return the decision records in number order, with their problems."""
    decisions = []
    for path in sorted(root.glob("*.md")):
        if path.name == "README.md":
            continue
        problems = []
        match = DECISION_FILE_RE.match(path.name)
        if not match:
            problems.append("file name must be NNNN-kebab-title.md")
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        title = ""
        for line in lines:
            if line.startswith("# "):
                # Records title themselves "N. Title"; the number is the file's.
                title = re.sub(r"^\d+\.\s+", "", line[2:].strip())
                break
        if not title:
            problems.append("first heading is the decision title")
        date = ""
        status = ""
        for line in lines[:12]:
            if line.startswith("Date:"):
                date = line[5:].strip()
            elif line.startswith("Status:"):
                status = line[7:].strip()
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
            problems.append("a `Date: YYYY-MM-DD` line follows the title")
        if not status.split(" ")[0] in DECISION_STATUSES:
            problems.append(f"a `Status:` line names one of {', '.join(DECISION_STATUSES)}")
        for heading in ("## Context", "## Decision", "## Consequences"):
            if heading not in lines:
                problems.append(f"section {heading!r} is missing")
        decisions.append({
            "file": path.name,
            "number": int(match.group(1)) if match else None,
            "title": title,
            "date": date,
            "status": status,
            "problems": problems,
        })
    numbers = [decision["number"] for decision in decisions if decision["number"] is not None]
    if numbers != list(range(1, len(numbers) + 1)):
        for decision in decisions:
            decision["problems"].append("decision numbers must be 0001, 0002, … without gaps or repeats")
    return decisions


def render_decisions_index(decisions):
    lines = [
        GENERATED_NOTICE,
        "",
        "# Decisions",
        "",
        "Architecture and product decision records, numbered in the order they were",
        "taken. A superseded record stays in place with its status changed; history is",
        "never rewritten. `CONTRIBUTING.md` says when a change needs one.",
        "",
        "| # | Decision | Status | Date |",
        "| --- | --- | --- | --- |",
    ]
    for decision in decisions:
        number = f"{decision['number']:04d}" if decision["number"] is not None else "?"
        lines.append(f"| {number} | [{decision['title']}]({decision['file']}) | {decision['status']} | {decision['date']} |")
    lines.append("")
    return "\n".join(lines)


# --- Entry points ----------------------------------------------------------


def generated_files(pages=None, decisions=None):
    """Return ``{path: content}`` for every file this module owns."""
    pages = pages if pages is not None else load_pages()
    decisions = decisions if decisions is not None else load_decisions()
    return {
        USERS / "README.md": render_users_index(pages),
        DECISIONS / "README.md": render_decisions_index(decisions),
        DOCS / "llms.txt": render_llms_txt(pages, decisions),
    }


def write_indexes():
    written = []
    for path, content in generated_files().items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            written.append(path)
    return written


def check(root=USERS):
    """Return a list of ``(path, problem)`` for everything wrong with the docs."""
    fm = frontmatter()
    findings = []
    pages = load_pages(root, fm)
    journeys = {}
    for page in pages:
        for problem in page.problems:
            findings.append((f"docs/users/{page.path}", problem))
        for problem in check_links(page, root):
            findings.append((f"docs/users/{page.path}", problem))
        journey = page.data.get("journey")
        if journey:
            if journey in journeys:
                findings.append((f"docs/users/{page.path}", f"journey {journey!r} is also claimed by {journeys[journey]}"))
            journeys[journey] = page.path
        for source in page.data.get("source") or []:
            if isinstance(source, str) and not (ROOT / source).exists():
                findings.append((f"docs/users/{page.path}", f"source {source!r} does not exist"))
    decisions = load_decisions()
    for decision in decisions:
        for problem in decision["problems"]:
            findings.append((f"docs/product/decisions/{decision['file']}", problem))
    for path, content in generated_files(pages, decisions).items():
        rel = path.relative_to(ROOT).as_posix()
        if not path.exists():
            findings.append((rel, "missing; run `make docs`"))
        elif path.read_text(encoding="utf-8") != content:
            findings.append((rel, "out of date; run `make docs`"))
    return findings


def coverage(pages=None):
    """Return ``{type: (test_backed, total)}`` for the coverage report."""
    pages = pages if pages is not None else load_pages()
    result = {}
    for page in pages:
        backed, total = result.get(page.type, (0, 0))
        result[page.type] = (backed + (1 if page.data.get("journey") else 0), total + 1)
    return result
