import json
import os
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path
from unittest.mock import patch

from odoo import Command
from odoo.tests import HttpCase, new_test_user, tagged

from ..controllers import user_docs

COMMIT = "0801ff5b7cf6a1b2c3d4e5f60718293a4b5c6d7e"
PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489"
    "0000000d49444154789c6360f8cfc00000030101c3ba0e9b0000000049454e44ae426082",
)


def _write_guide(root):
    """A three-page guide: a tested how-to, a hand-written explanation, an image."""
    root = Path(root)
    (root / "how-to").mkdir()
    (root / "how-to" / "example").mkdir()
    (root / "explanation").mkdir()
    (root / "README.md").write_text(
        "<!-- Generated by scripts/docs-index. -->\n\n# Guide\n\nStart with [the example](how-to/example.md).\n",
        encoding="utf-8",
    )
    (root / "how-to" / "example.md").write_text(
        "---\n"
        "title: Do the example\n"
        "type: how-to\n"
        "description: An example journey.\n"
        "lang: en\n"
        "persona: accountant\n"
        "journey: usl_docs.example\n"
        "source:\n"
        "  - custom-addons/usl_docs/controllers/user_docs.py\n"
        "generated: true\n"
        "---\n\n"
        "# Do the example\n\n"
        "1. Open the screen.\n\n"
        "   ![The screen](example/01-open.png)\n\n"
        "See [the explanation](../explanation/why.md#reason).\n",
        encoding="utf-8",
    )
    (root / "how-to" / "example" / "01-open.png").write_bytes(PNG)
    (root / "explanation" / "why.md").write_text(
        "---\n"
        "title: Pourquoi\n"
        "type: explanation\n"
        "description: Why it is so.\n"
        "lang: fr\n"
        "generated: false\n"
        "---\n\n"
        "# Pourquoi\n\n## Reason\n\nParce que.\n",
        encoding="utf-8",
    )
    return root


@tagged("post_install", "-at_install", "usl_docs")
class TestUserDocsViewer(HttpCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.reader = new_test_user(
            cls.env,
            login="usl-docs-reader",
            password="docs-reader",
            groups="base.group_user",
            company_id=cls.env.company.id,
            company_ids=[Command.set(cls.env.company.ids)],
        )
        cls.portal = new_test_user(
            cls.env,
            login="usl-docs-portal",
            password="docs-portal",
            groups="base.group_portal",
        )

    def setUp(self):
        super().setUp()
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = _write_guide(self.tmp.name)
        patcher = patch.dict(os.environ, {user_docs.DOCS_ENV_VAR: str(self.root)})
        patcher.start()
        self.addCleanup(patcher.stop)
        user_docs._evidence_from_file.cache_clear()

    def _get(self, path, **kwargs):
        return self.url_open(user_docs.DOCS_ROUTE + path, **kwargs)

    def test_every_internal_user_can_read_the_guide(self):
        self.authenticate("usl-docs-reader", "docs-reader")
        response = self._get("")
        self.assertEqual(response.status_code, 200)
        self.assertIn("Start with", response.text)
        self.assertNotIn("Generated by scripts/docs-index", response.text, "HTML comments must not print")
        # Sections appear in Diátaxis order and titles come from front matter.
        self.assertLess(response.text.index("How-to guides"), response.text.index("Explanation"))
        self.assertIn("Do the example", response.text)
        self.assertIn('<span class="doc-lang">FR</span>', response.text)

    def test_a_portal_user_is_told_nothing(self):
        self.authenticate("usl-docs-portal", "docs-portal")
        self.assertEqual(self._get("").status_code, 404)

    def test_a_page_carries_its_pills_sources_and_footer(self):
        self.authenticate("usl-docs-reader", "docs-reader")
        response = self._get("/how-to/example.md")
        self.assertEqual(response.status_code, 200)
        self.assertIn('<html lang="en">', response.text)
        self.assertIn("How-to guide", response.text)
        self.assertIn("For accountants", response.text)
        self.assertIn("Unverified build", response.text)
        self.assertIn(
            "https://github.com/unstaticlabs/odoo/blob/19-usl-staging/custom-addons/usl_docs/controllers/user_docs.py",
            response.text,
        )
        self.assertIn("generated from the journey", response.text)
        self.assertNotIn("title: Do the example", response.text, "front matter must not render as text")
        # Relative images and links are rewritten into the guide's own route.
        self.assertIn('src="/usl/user-docs/how-to/example/01-open.png"', response.text)
        self.assertIn('href="/usl/user-docs/explanation/why.md#reason"', response.text)

    def test_a_hand_written_page_says_so(self):
        self.authenticate("usl-docs-reader", "docs-reader")
        response = self._get("/explanation/why.md")
        self.assertIn('<html lang="fr">', response.text)
        self.assertIn("Not test-backed", response.text)
        self.assertIn("written by hand", response.text)

    def test_sources_link_to_the_running_release(self):
        self.env["ir.config_parameter"].sudo().set_str("usl.release.commit", COMMIT)
        self.authenticate("usl-docs-reader", "docs-reader")
        response = self._get("/how-to/example.md")
        self.assertIn(f"/blob/{COMMIT}/custom-addons/usl_docs/controllers/user_docs.py", response.text)

    def test_images_are_served_and_traversal_is_refused(self):
        self.authenticate("usl-docs-reader", "docs-reader")
        image = self._get("/how-to/example/01-open.png")
        self.assertEqual(image.status_code, 200)
        self.assertEqual(image.headers["Content-Type"], "image/png")
        self.assertEqual(image.content, PNG)
        self.assertEqual(self._get("/../../etc/passwd").status_code, 404)
        self.assertEqual(self._get("/how-to/../../README.md").status_code, 404)
        self.assertEqual(self._get("/how-to/missing.md").status_code, 404)

    def test_an_agent_gets_the_committed_markdown(self):
        self.authenticate("usl-docs-reader", "docs-reader")
        response = self._get("/how-to/example.md", headers={"Accept": "text/markdown"})
        self.assertEqual(response.headers["Content-Type"], "text/markdown; charset=utf-8")
        self.assertTrue(response.text.startswith("---\ntitle: Do the example\n"))
        response = self._get("/how-to/example.md?format=md")
        self.assertEqual(response.headers["Content-Type"], "text/markdown; charset=utf-8")
        index = self._get("/llms.txt")
        self.assertEqual(index.headers["Content-Type"], "text/markdown; charset=utf-8")
        self.assertTrue(index.text.startswith("# USL User Guide\n\n> "))
        self.assertIn("## How-to guides\n\n- [Do the example](http://", index.text)
        self.assertIn("/usl/user-docs/how-to/example.md?format=md): An example journey.", index.text)
        self.assertIn("## Optional\n\n- [Pourquoi](", index.text)

    def test_the_evidence_pill_reads_the_shipped_evidence(self):
        finished = (datetime.now(timezone.utc) - timedelta(days=2, hours=1)).isoformat()
        evidence = Path(self.tmp.name) / "docs-evidence.json"
        evidence.write_text(
            '{"schema": "usl-docs-evidence/v1", "qualified_commit": "%s", '
            '"run_url": "https://github.com/unstaticlabs/odoo/actions/runs/1", '
            '"journeys": {"usl_docs.example": {"status": "success", "finished": "%s"}}}'
            % (COMMIT, finished),
            encoding="utf-8",
        )
        self.env["ir.config_parameter"].sudo().set_str("usl.release.commit", COMMIT)
        self.authenticate("usl-docs-reader", "docs-reader")
        with patch.dict(os.environ, {user_docs.EVIDENCE_ENV_VAR: str(evidence)}):
            response = self._get("/how-to/example.md")
        self.assertIn("Last tested 2 days ago · proof", response.text)
        self.assertIn('href="/usl/user-docs/evidence/usl_docs.example"', response.text)

    def test_the_evidence_stamped_into_the_database_is_read_and_has_a_proof_page(self):
        """At deploy the release stamps usl.docs.evidence; the proof page shows it."""
        finished = (datetime.now(timezone.utc) - timedelta(hours=5)).isoformat()
        evidence = {
            "schema": "usl-docs-evidence/v1",
            "qualified_commit": COMMIT,
            "workflow_run_id": 77,
            "run_url": "https://github.com/unstaticlabs/odoo/actions/runs/77",
            "chromium": "Chrome/152",
            "journeys": {
                "usl_docs.example": {
                    "status": "success",
                    "page": "how-to/example.md",
                    "tour": "usl_docs_example",
                    "source_test": "odoo.addons.usl_docs.tests.test_x.TestX.test_y",
                    "started": "2026-09-08T10:00:00Z",
                    "finished": finished,
                    "viewports": ["desktop"],
                    "screenshots": [
                        {"step": "open", "viewport": "desktop", "file": "01-open.png", "match": "exact"},
                    ],
                },
            },
        }
        self.env["ir.config_parameter"].sudo().set_str(user_docs.EVIDENCE_PARAMETER, json.dumps(evidence))
        self.env["ir.config_parameter"].sudo().set_str("usl.release.commit", COMMIT)
        self.authenticate("usl-docs-reader", "docs-reader")
        page = self._get("/how-to/example.md")
        self.assertIn("Last tested 5 hours ago · proof", page.text)
        proof = self._get("/evidence/usl_docs.example")
        self.assertEqual(proof.status_code, 200)
        self.assertIn("Proof for “Do the example”", proof.text)
        self.assertIn("GitHub run 77", proof.text)
        self.assertIn("matches the published screenshot", proof.text)
        self.assertIn(COMMIT, proof.text)
        self.assertEqual(self._get("/evidence/unknown").status_code, 404)
        self.authenticate("usl-docs-portal", "docs-portal")
        self.assertEqual(self._get("/evidence/usl_docs.example").status_code, 404)


@tagged("post_install", "-at_install", "usl_docs")
class TestEvidenceState(HttpCase):
    """What the pill says in every situation a release can be in."""

    PAGE = {"type": "how-to", "journey": "usl_docs.example"}

    def test_states(self):
        now = datetime(2026, 9, 10, 12, 0, tzinfo=timezone.utc)
        tested = {
            "qualified_commit": COMMIT,
            "run_url": "https://example.test/run",
            "journeys": {"usl_docs.example": {"status": "success", "finished": "2026-09-08T11:00:00Z"}},
        }
        cases = [
            ({"type": "explanation"}, None, "not-test-backed"),
            (self.PAGE, None, "unverified"),
            (self.PAGE, {"mode": "recovery"}, "recovery"),
            (self.PAGE, {"journeys": {}}, "untested-release"),
            (self.PAGE, tested, "tested"),
        ]
        for page, evidence, kind in cases:
            with self.subTest(kind=kind):
                state = user_docs.evidence_state(page, evidence, COMMIT, now)
                self.assertEqual(state["kind"], kind)
        state = user_docs.evidence_state(self.PAGE, tested, COMMIT, now)
        self.assertEqual(state["label"], "Last tested 2 days ago")
        self.assertEqual(state["run_url"], "https://example.test/run")
        self.assertEqual(state["detail"], "")
        other = user_docs.evidence_state(self.PAGE, tested, "f" * 40, now)
        self.assertIn("different commit", other["detail"])

    def test_relative_age_reads_like_a_person(self):
        now = datetime(2026, 9, 10, 12, 0, tzinfo=timezone.utc)
        for delta, expected in [
            (timedelta(seconds=30), "just now"),
            (timedelta(minutes=5), "5 minutes ago"),
            (timedelta(hours=1), "an hour ago"),
            (timedelta(hours=5), "5 hours ago"),
            (timedelta(days=1), "a day ago"),
            (timedelta(days=6), "6 days ago"),
            (timedelta(days=21), "3 weeks ago"),
            (timedelta(days=100), "3 months ago"),
            (timedelta(days=400), "a year ago"),
        ]:
            self.assertEqual(user_docs.relative_age(now - delta, now), expected)
