{
    "name": "USL B2C Sales and Inventory",
    "summary": "Auditable B2C commerce history and native operational workflows",
    "version": "saas~19.3.1.2.0",
    "category": "Sales/Sales",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "account_payment",
        "delivery",
        "mrp",
        "payment",
        "purchase",
        "purchase_stock",
        "sale_management",
        "sale_margin",
        "sale_stock",
        "stock_account",
        "stock_landed_costs",
        "usl_accounting",
    ],
    "data": [
        "security/b2c_security.xml",
        "security/ir.model.access.csv",
        "views/channel_views.xml",
        "views/product_alias_views.xml",
        "views/order_views.xml",
        "views/event_views.xml",
        "views/accounting_views.xml",
        "views/evidence_views.xml",
        "views/product_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
    "post_init_hook": "post_init_hook",
}
