# ruff: noqa: I001 - attachment bridge extends models declared above
from . import (
    business_record,
    document,
    document_intake,
    document_lifecycle,
    document_link,
    document_mcp,
    document_operation,
    document_search,
    document_sync,
    document_version,
    document_workspace,
    download_grant,
    metadata,
    document_views,
    paperless_client,
    paperless_user_mapping,
    pocketid,
    res_config_settings,
    res_users,
    attachment_bridge,
    attachment_native,
)
