{
    "name": "USL Sign",
    "summary": "Odoo-native signatures with reinforced local evidence",
    "description": "Standard, strong personal and provider-neutral qualified signing workflows.",
    "version": "saas~19.3.2.0.0",
    "category": "Productivity/Sign",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "sign_oca",
        "mail",
        "portal",
        "usl_locale",
        "usl_pocketid",
        "usl_documents",
    ],
    "external_dependencies": {
        "python": ["opentimestamps"],
    },
    "data": [
        "security/usl_sign_security.xml",
        "security/ir.model.access.csv",
        "data/sign_data.xml",
        "data/mail_templates.xml",
        "data/sign_cron.xml",
        "views/sign_policy_views.xml",
        "views/sign_template_views.xml",
        "views/sign_configuration_views.xml",
        "views/sign_template_generate_views.xml",
        "views/sign_workspace_views.xml",
        "views/sign_request_views.xml",
        "views/sign_enrollment_views.xml",
        "views/sign_external_views.xml",
        "views/sign_daily_manifest_views.xml",
        "views/sign_service_status_views.xml",
        "views/sign_portal_templates.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/sign_menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "usl_sign/static/src/js/business_summary.esm.js",
            "usl_sign/static/src/js/enrollment_actions.esm.js",
            "usl_sign/static/src/js/signing_method_radio.esm.js",
            "usl_sign/static/src/js/systray_patch.esm.js",
            "usl_sign/static/src/js/workspace.esm.js",
            "usl_sign/static/src/js/signature_inspector_utils.esm.js",
            "usl_sign/static/src/js/signature_inspector.esm.js",
            "usl_sign/static/src/js/document_preview_field.esm.js",
            "usl_sign/static/src/js/template_library.esm.js",
            "usl_sign/static/src/js/editor_utils.esm.js",
            "usl_sign/static/src/js/configure_patch.esm.js",
            "usl_sign/static/src/xml/business_summary.xml",
            "usl_sign/static/src/xml/workspace.xml",
            "usl_sign/static/src/xml/signature_inspector.xml",
            "usl_sign/static/src/xml/document_preview_field.xml",
            "usl_sign/static/src/xml/template_library.xml",
            "usl_sign/static/src/xml/configure_patch.xml",
            "usl_sign/static/src/xml/signing_method_radio.xml",
            "usl_sign/static/src/xml/systray_patch.xml",
            "usl_sign/static/src/scss/sign.scss",
        ],
        "web.assets_unit_tests": [
            "usl_sign/static/tests/document_preview_field.test.js",
            "usl_sign/static/tests/enrollment_actions.test.js",
            "usl_sign/static/tests/editor_utils.test.js",
            "usl_sign/static/tests/editor_interactions.test.js",
            "usl_sign/static/tests/template_library.test.js",
            "usl_sign/static/tests/workspace.test.js",
            "usl_sign/static/tests/signature_inspector_utils.test.js",
            "usl_sign/static/tests/signature_inspector.test.js",
            "usl_sign/static/tests/signing_method_radio.test.js",
        ],
        "web.assets_tests": [
            ("remove", "sign_oca/static/src/tests/sign_tour.esm.js"),
        ],
        "oca_sign.assets_frontend_sign": [
            "usl_sign/static/src/js/portal_patch.esm.js",
            "usl_sign/static/src/xml/portal_patch.xml",
            "usl_sign/static/src/scss/sign.scss",
        ],
        "usl_sign.assets_strong": [
            "web/static/src/libs/fontawesome/css/font-awesome.css",
            "usl_sign/static/src/scss/strong_sign.scss",
        ],
    },
    "application": True,
    "installable": True,
    "post_init_hook": "post_init_hook",
}
