{
    "name": "USL Pocket ID SSO",
    "summary": "Hardened Pocket ID OIDC login and governed identity linking",
    "version": "saas~19.3.1.3.0",
    "category": "Tools",
    "author": "Unstatic Labs",
    "license": "LGPL-3",
    "depends": [
        "account",
        "auth_oidc",
        "auth_passkey",
        "hr_expense",
        "mail",
        "portal",
        "project",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/sender_alias_security.xml",
        "data/pocketid_provider.xml",
        "data/mail_templates.xml",
        "views/auth_oauth_provider_views.xml",
        "views/oidc_identity_views.xml",
        "views/res_users_views.xml",
        "views/res_users_identitycheck_views.xml",
        "views/sender_alias_views.xml",
        "views/sender_alias_templates.xml",
        "views/login_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "usl_pocketid/static/src/js/pocketid_reauthentication.js",
            "usl_pocketid/static/src/js/check_identity.js",
            "usl_pocketid/static/src/js/identity_check_form.js",
            "usl_pocketid/static/src/xml/check_identity.xml",
        ],
    },
    "application": False,
    "installable": True,
}
